### ISSUE TITLE
Дочистить техническую реализацию вектора

### ISSUE THREAD

**Issue by avasyukov** [sidjuli/2sem_1task#1]
Логически код вектора адекватен. Осталось дочистить методы, расставив const-ы там, где они должны быть. В итоге вот такой main должен успешно собираться и работать:
```c++
int main()
{
    std::cout << "=== Test vector ===" << std::endl;

    Vector2D v1 = {1, 1};
    Vector2D v2 = {2, 2};

    std::cout << (v1 + v2) << std::endl;
    std::cout << (v1 - v2) << std::endl;
    std::cout << v1 * 5 << std::endl;
    std::cout << -5 * v2 << std::endl;
    std::cout << v1 << std::endl;
    std::cout << v2 << std::endl;

    std::cout << v1 * v2 << std::endl;

    return 0;
}
```

**Comment by sidjuli** [comment]
Здесь тоже исправила, всё работает. Только у меня другой способ задания векторов. Вместо Vector2D v1 = {1, 1}; я использовала Vector2D v1(1, 1)

**Comment by avasyukov** [comment]
Подтверждаю, починено. Инит ```Vector2D v1 = {1, 1} ``` и ```Vector2D v1(1, 1)``` - это примерно одно и то же в разной записи. В подробности лезть на сейчас не будем.

(Ну и ждём допиленные матрицы. Текущий вид исходника внушает оптимизм, нужно оформить это всё перегрузкой операторов. Ну и дописать умножение матрицы на вектор.)
