### ISSUE TITLE
Скалярное произведение векторов

### ISSUE THREAD

**Issue by avasyukov** [sidjuli/2sem_1task#2]
Вот здесь:
https://github.com/sidjuli/2sem_1task/blob/e8243bc6be46da737562656e45441f381946c1aa/Vector2D.cpp#L51-L56
сделать скалярное произведение. По заданию было нужно оно. Покоординатное произведение векторов - нечто довольно странное.

**Comment by sidjuli** [comment]
Исправила, теперь функция возвращает значение скалярного произвеления

**Comment by avasyukov** [comment]
Подтверждаю, починено. Тикет закрываю.
